name: Main
on: workflow_dispatch
jobs:
  Desktop:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-12, macos-14]
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6

      - name: Install libVLC (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt install libvlc-dev libvlccore-dev

      - name: Install Libraries
        run: |
          haxelib install lime 8.1.2 --quiet
          haxelib install openfl 9.3.4 --quiet
          haxelib install flixel 5.6.1 --quiet
          haxelib install flixel-ui 2.6.1 --quiet
          haxelib install flixel-addons 3.2.2 --quiet
          haxelib install flixel-tools 1.5.1 --quiet
          haxelib install SScript 7.7.0 -quiet
          haxelib install tjson 1.4.0 --quiet
          haxelib git flxanimate https://github.com/Dot-Stuff/flxanimate 768740a56b26aa0c072720e0d1236b94afe68e3e --quiet
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit 1906c4a96f6bb6df66562b3f24c62f4c5bba14a7 --quiet
          haxelib git hxdiscord_rpc https://github.com/MAJigsaw77/hxdiscord_rpc 3538a1c2bb07b04208cd014220207f8173acdb21 --quiet --skip-dependencies
          haxelib git hxvlc https://github.com/MAJigsaw77/hxvlc 70e7f5f3e76d526ac6fb8f0e6665efe7dfda589d --quiet --skip-dependencies
          haxelib git funkin.vis https://github.com/FunkinCrew/funkVis d5361037efa3a02c4ab20b5bd14ca11e7d00f519 --quiet --skip-dependencies
          haxelib git grig.audio https://gitlab.com/haxe-grig/grig.audio.git cbf91e2180fd2e374924fe74844086aab7891666 --quiet
          haxelib install markdown
          haxelib install away3d
          haxelib install UnRAR

      - name: Compile (Windows)
        if: startsWith(matrix.os, 'windows')
        run: haxelib run lime build windows

      - name: Compile (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: haxelib run lime build linux

      - name: Compile (macOS)
        if: startsWith(matrix.os, 'macos')
        run: haxelib run lime build mac

      - name: Upload Artifact (Windows)
        if: startsWith(matrix.os, 'windows')
        uses: actions/upload-artifact@main
        with:
          name: windowsBuild
          path: export\release\windows\bin\*
          if-no-files-found: error

      - name: Upload Artifact (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        uses: actions/upload-artifact@main
        with:
          name: linuxBuild
          path: export/release/linux/bin/*
          if-no-files-found: error

      - name: Upload Artifact (macOS 12)
        if: matrix.os == 'macos-12'
        uses: actions/upload-artifact@main
        with:
          name: macOSBuild-x86_64
          path: export/release/macos/bin/*
          if-no-files-found: error

      - name: Upload Artifact (macOS 14)
        if: matrix.os == 'macos-14'
        uses: actions/upload-artifact@main
        with:
          name: macOSBuild-arm64
          path: export/release/macos/bin/*
          if-no-files-found: error
  Mobile:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-14]
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6

      - name: Install Libraries
        run: |
          haxelib git hxcpp https://github.com/mcagabe19-stuff/hxcpp --quiet
          haxelib git lime https://github.com/mcagabe19-stuff/lime --quiet
          haxelib install openfl 9.3.3 --quiet
          haxelib install flixel 5.6.1 --quiet
          haxelib install flixel-addons 3.2.2 --quiet
          haxelib install flixel-tools 1.5.1 --quiet
          haxelib install hscript-iris 1.0.2
          haxelib install tjson 1.4.0 --quiet
          haxelib git flxanimate https://github.com/Dot-Stuff/flxanimate 768740a56b26aa0c072720e0d1236b94afe68e3e --quiet
          if [[ "${{ runner.os }}" == "macOS" ]] ; then
            haxelib git linc_luajit https://github.com/superpowers04/linc_luajit 1906c4a96f6bb6df66562b3f24c62f4c5bba14a7 --quiet
          else
            haxelib git linc_luajit https://github.com/mcagabe19-stuff/linc_luajit-legacy --quiet --skip-dependencies
          fi
          haxelib git hxdiscord_rpc https://github.com/MAJigsaw77/hxdiscord_rpc 3538a1c2bb07b04208cd014220207f8173acdb21 --quiet --skip-dependencies
          haxelib git hxvlc https://github.com/MAJigsaw77/hxvlc 70e7f5f3e76d526ac6fb8f0e6665efe7dfda589d --quiet --skip-dependencies
          haxelib git funkin.vis https://github.com/FunkinCrew/funkVis d5361037efa3a02c4ab20b5bd14ca11e7d00f519 --quiet --skip-dependencies
          haxelib git grig.audio https://gitlab.com/haxe-grig/grig.audio.git cbf91e2180fd2e374924fe74844086aab7891666 --quiet
          haxelib git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools 727693f0a76c6e396df675bb0ed95d7639a4db01 --quiet --skip-dependencies

      - name: Configure Android
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME_17_X64
          haxelib run lime config ANDROID_SETUP true

      - name: Compile (Android)
        if: startsWith(matrix.os, 'ubuntu')
        run: haxelib run lime build android -D officialBuild

      - name: Compile (iOS)
        if: startsWith(matrix.os, 'macos')
        run: haxelib run lime build ios -nosign -D officialBuild

      - name: Make Ipa
        if: startsWith(matrix.os, 'macos')
        run: |
          cd export/release/ios/build/*-iphoneos
          mkdir Payload
          mv *.app Payload
          zip -r PsychEngine.ipa Payload

      - name: Upload Artifact (Android)
        if: startsWith(matrix.os, 'ubuntu')
        uses: actions/upload-artifact@main
        with:
          name: androidBuild
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
          if-no-files-found: error

      - name: Upload Artifact (iOS)
        if: startsWith(matrix.os, 'macos')
        uses: actions/upload-artifact@main
        with:
          name: iOSBuild
          path: export/release/ios/build/Release-iphoneos/*.ipa
          if-no-files-found: error